server:
  port: 8050

parser:
  songsOnPage: '50'
  schedulerConfig: 30 0 2,14 * * *

spring:
  datasource:
    url: jdbc:h2:mem:default
    username: h2user
    password: h2pass
    driverClassName: org.h2.Driver
  jpa:
    spring:
      jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        properties:
          hibernate:
            check_nullability: true